project:
  type: website
  output-dir: docs

website:
  title: "Spyros Balafas, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research & Software
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
    right:
      - icon: github
        href: https://github.com/SpyBal
      - icon: envelope
        href: mailto:sp.balafas@gmail.com

format:
  html:
    theme: cosmo
    toc: true