---
title: "Publications"
---

### 2026
* **Balafas, S.**, et al. [cite_start]"A temporal network analysis of drug co-prescription during antidepressants and anxiolytics dispensing in the Netherlands from 2018 to 2022," *Global Epidemiology*. [cite: 116]

### 2025
* **Zhou, G., ..., Balafas, S.**, et al. [cite_start]"Effectiveness of COVID-19 vaccines against SARS-CoV-2 infection and severe outcomes in adults: a systematic review and meta-analysis," *European Respiratory Review*. [cite: 103]
* **Castelnovo, A., ..., Balafas, S.**, et al. [cite_start]"Spectral Dynamics Prior to Motor Events Differ Between NREM Sleep Parasomnias and Healthy Sleepers," *Sleep*. [cite: 103]

### 2024
* **Andreella, A., ..., Balafas, S.**, et al. [cite_start]"A predictive model for planning emergency events rescue during COVID19 in Lombardy, Italy," *Statistical Methods & Applications*. [cite: 103]
* **Balafas, S.**, et al. [cite_start]"Comparing Healthcare Fundraising Campaigns using Psychophysiological Data: a Network Based Approach," *Statistical Methods & Applications*. [cite: 103]